# Generated by Django 3.1.7 on 2021-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210311_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phonenumber',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
