# Generated by Django 3.1.7 on 2021-03-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210311_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phonenumber',
            new_name='number',
        ),
    ]
