# Generated by Django 3.1.7 on 2021-03-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
