# Generated by Django 3.1.7 on 2021-03-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
